github_token: ""
repo: "sarfarazahmad19/opencode-k8s"
labels:
  - updatecli
  - traefik
label: "traefik"
flux_namespace: "flux-system"
gitrepo_name: "flux-system"
test_namespace: "flux-system"
poll_interval: 300
