github_token: ""
repo: "sarfarazahmad19/opencode-k8s"
repo_path: "/datadrive/home/ahmad/git/opencode-k8s"
ssh_key_path: "/home/ahmad/.ssh/id_rsa"
labels:
  - updatecli
  - traefik
label: "traefik"
flux_namespace: "flux-system"
gitrepo_name: "flux-system"
helmrelease_namespace: "traefik"
test_namespace: "traefik"
poll_interval: 300
